Hello Microverse Project Pull request
Muhammad0602/hello-microverse pull request #1
Opened 2023-01-10 21:59 UTC by Muhammad0602

Add the html and css needed for the project

2023-01-11 16:13 UTC, osamaashraf6 requested changes
Hi @Muhammad0602 👋, 

Good job so far! 👏🥳
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![ItsJustATinyChangeSheaWhitneyGIF](https://user-images.githubusercontent.com/83360636/211856207-5e29b25a-ffbb-4dbd-a675-bc95a3cc0f4a.gif)


## Highlights ✔️


- [ ] No linter errors. 💯
- [ ] Good usage in correcting GitHub flow
- [ ] Descriptive pull request




## Required Changes ♻️

- [ ] You did well👌, but Kindly use 😃[the Microverse Readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) and make sure all the main sections present in yours and placeholders are replaced with your project and personal data. The only optional section is a FAQ. Please remove the template logo on the top, if you have one, you can replace it. This is crucial to have a professional and instructive repository. 👌
- [ ] Please consider💯 using best practices when you write commit messages, they should be capitalized sentences in the imperative form, for example: "Fix css" instead of "fixing css"  ... etc 👍



## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-11 18:02 UTC, Gambit142 requested changes
Hi @Muhammad0602 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- The project has an index.html file ✔️ 
- The project has a style.css file ✔️ 
- Pull request title is self-explanatory ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

- Kindly configure the linters for this project. For all the projects that you will execute in Microverse, you would need to configure linters. Linters help us to write clean, readable and maintainable codes. For this project, kindly follow the instructions in this article 
https://github.com/microverseinc/linters-config/tree/master/html-css 💻 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 18:02 UTC, Gambit142 commented on README.md
> +
- [ ]  Great job working on the changes as requested by the previous reviewer. As the reviewer mentioned all main sections should be present and each section should have their customized information based on the project being executed. 👍 For the **_Tech Stack_** Section, Kindly remove the _**Server**_ and _**Database**_ subsections because the technologies listed there are not relevant to this project. For the _**Client**_ section, kindly include `HTML` and `CSS` 👍

2023-01-11 18:02 UTC, Gambit142 commented on README.md
> + -->
- For the **_Prerequisite_** Section, kindly add tools that are needed before you can clone this repository on a local machine. Tools like:
  - Installation of `Git`
  - Installation of `NPM`
  - A working browser
  - Internet connection
  - A code editor like `Visual Studio Code`
  - Installation of `Live Server` plugging in Visual Studio Code
  - Any other tool you can think about 👍 💻

2023-01-11 18:02 UTC, Gambit142 commented on README.md
> +
- [ ] Kindly personalize this to be the repository link created when you want to clone this repository. 👍

2023-01-11 18:02 UTC, Gambit142 commented on README.md
> +<!--
- [ ] `gem install` is used for a Ruby on Rails project. For this section, I would advise you to include instructions for running the various linters that should be used for the HTML and CSS projects. 👍

2023-01-11 18:02 UTC, Gambit142 commented on README.md
> +
- [ ] `rails server` is used for a Ruby on Rails project. For this section, I would advise you to include instructions for opening this project on a browser. For example, opening the project by launching the Live Server plugging in visual studio code or any other means that you know.

2023-01-11 18:02 UTC, Gambit142 commented on README.md
> +
- [ ] Kindly remove this, it is for Ruby on Rails projects. 👍

2023-01-11 18:02 UTC, Gambit142 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Currently, when I click the link titled _**MIT**_ in the README.md file, it redirects me to an error page (check the image attached below). 

![image](https://user-images.githubusercontent.com/77106962/211882471-7be3ecf8-d1ce-4ccc-b1ec-f764b876778a.png)

#### To resolve this issue, kindly add a valid **_LICENSE_**. You can follow the instructions on the right side of the article link attached below to set up a valid LICENSE
https://choosealicense.com/licenses/mit/. I would advise that you name the file _**LICENSE**_. 💻 😄

2023-01-12 10:18 UTC, Abdessittir approved these changes
Hi @Muhammad0602 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights
✅ Good readme file
✅ Good GitHub flow
## Optional suggestions
- Please check the comments below

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 10:18 UTC, AHP15 commented on index.html
> +  <h1>Hello Microverse!</h1>
-[OPTIONAL] Please add a `class` attribute for this `h1` tag because it's in the requirements

2023-01-12 10:18 UTC, AHP15 commented on style.css
> +h1 {
-[OPTIONAL] Kindly use a `class` selector for this style because it's in the requirements

2023-01-12 12:39 UTC, merged